language: node_js
services: 
  - redis-server
node_js:
  - "7.6"
install: 
  - npm install
script: 
  - npm test
after_script:
  - npm run cov
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage